- .coveragerc
- Makefile
- evergreen.py
- test_dependabot_file.py
- test_evergreen.py
fixes #5 
This pull request includes changes to improve the test coverage and code quality. The most important changes include adding a `.coveragerc` file to omit test files from coverage, increasing the coverage threshold in the `Makefile`, adding `# pragma: no cover` to the `main()` function in `evergreen.py`, and modifying test cases in `test_dependabot_file.py` and `test_evergreen.py`.
Coverage improvements:
* [`.coveragerc`](diffhunk://#diff-834e9b406d74791ffbafaeec9cc894082cea9739bc347b6ff9f72312c92ebc79R1-R4): Added a new file to omit test files from coverage.
* [`Makefile`](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L3-R3): Increased the coverage threshold from 50 to 80.
* [`evergreen.py`](diffhunk://#diff-b2e641407994f0e45d80e45129e5d0388cc50c …
> Configure test coverage files and add tests

- evergreen.py
fixes #19 
This pull request includes a change to the `main` function in the `evergreen.py` file. The change introduces error handling for the `commit_changes` function call. If a `NotFoundError` is raised by `github3`, a message is printed to the console indicating that the pull request creation failed due to insufficient write permissions.
> Handle pull request write failures

- env.py
- test_env.py
Fix `DRY_RUN` always being `True`
Fix `DRY_RUN` always being set to `True` regardless of whether the value is configured as `true` or `false`.
Fixes #27.
> Fix DRY_RUN always being true

- README.md
Updates the basic and advanced workflow examples to use a weekly `schedule` cadence, rather than monthly.
Fixes https://github.com/github/evergreen/issues/51.
With this change, the example cron workflow will run [weekly on Saturdays](https://crontab.guru/#3_2_*_*_6).
> Use weekly cadence for workflow examples

- .github/linters/.jscpd.json
The ignore directive of jscpd is not working as expected
Fixes https://github.com/github/evergreen/pull/60
> The ignore directive of jscpd is not working as expected

- evergreen.py
- test_evergreen.py
> fix: remove time of day and tz info properly

- .env-example
- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/dependabot.yml
- README.md
> docs: add github issue templates

- dependabot_file.py
- test_dependabot_file.py
fixes #70
This pull request includes changes to the `dependabot_file.py` and `test_dependabot_file.py` files, specifically in the `build_dependabot_file` function and the `test_build_dependabot_file_with_hex` test case. The changes are focused on replacing the package ecosystem from 'hex' to 'mix'.
> fix: referring to mix package key as hex.

- evergreen.py
to enhance debug experience when nothing prints for minutes on end.
This pull request includes changes to the `evergreen.py` file, specifically in the `main()` function. The changes are focused on adding print statements to provide more detailed feedback during the execution of the function. This will help in understanding the flow of the function and the reasons for skipping certain repositories.
> chore: add skip debug prints

- .github/dependabot.yml
- env.py
- requirements-test.txt
- test_env.py
Closes #104
Closes #105
Add commit-message.prefix config option to dependabot so that dependabot pull request titles pass our new PR Title Linting workflow
> chore(deps): update dependabot config to include pr prefixes

- dependabot_file.py
- test_dependabot_file.py
Fix spacing on dependabot.yaml output
> fix: yaml hierarchy indicates 2 spaces instead of 4

- .github/workflows/auto-labeler.yml
- .github/workflows/contributors_report.yaml
- .github/workflows/docker-ci.yml
- .github/workflows/major-version-updater.yml
- .github/workflows/pr-title.yml
- .github/workflows/python-ci.yml
- .github/workflows/release.yml
- .github/workflows/scorecard.yml
- .github/workflows/stale.yaml
- .github/workflows/super-linter.yaml
- README.md
Relates to github/github-ospo#84
Relates to github/github-ospo#95
> chore: add OSSF scorecard github action and README badge

- .github/workflows/release.yml
I am not worried about the security implications with us checking out the forked pull requests code. This action only fires after a merge to main so this means the pull request code has been reviewed by a maintainer. We are post-CI/code run.
> chore: add pull_request_target for releases

- test_dependabot_file.py
fixes #152
This pull request introduces a new test case to ensure the correct generation of dependabot configuration files for Terraform projects within the `test_dependabot_file.py` file. 
- **Adds a new test case**: Implements `test_build_dependabot_file_with_terraform` to verify that dependabot configuration files correctly include Terraform as a package ecosystem when Terraform files are present in the repository.
- **Handles absence of Terraform files and no files at all**: Enhances the test to also verify that no Terraform entry is added to the dependabot configuration file when no Terraform files are present in the repository.
> ci: Add test for Terraform dependabot config

- test_dependabot_file.py
Fixes #156
This pull request introduces tests for the GitHub Actions dependabot configuration in the `test_dependabot_file.py` file, enhancing the test coverage for dependabot configurations.
- **Adds new tests**: Implements two new test methods, `test_build_dependabot_file_with_github_actions` and `test_build_dependabot_file_with_github_actions_without_files`.
- The first test ensures that the dependabot configuration for GitHub Actions is correctly generated when YAML files are present in the `.github/workflows` directory.
- The second test verifies that the dependabot configuration is `None` when no YAML files are found in the `.github/workflows` directory, aligning with the expected behavior for repositories without GitHub Actions workflows.
> ci: Add test for GitHub Actions dependabot configuration

- .github/workflows/auto-labeler.yml
- .github/workflows/docker-ci.yml
- .github/workflows/major-version-updater.yml
- .github/workflows/pr-title.yml
- .github/workflows/python-ci.yml
- .github/workflows/release.yml
- .github/workflows/scorecard.yml
- .github/workflows/super-linter.yaml
- env.py
- test_env_get_bool.py
> chore: standardize github action types

- evergreen.py
Fix https://github.com/github/evergreen/issues/168
Set a default value to dependabot_filename_to_use rather than `None`
> fix: Add a default value for dependabot_filename_to_use

- evergreen.py
- test_evergreen.py
fixes #208 
Simplify and correct the handling of the `update_existing` parameter when checking for existing Dependabot configuration files. The most important changes include removing the `update_existing` parameter from the `check_existing_config` function and updating the surrounding logic accordingly. This should result in fixing the situation described in #208. I did have to remove a test now that the `update_existing` parameter is no longer used in the `check_existing_config` function.
> fix: update_existing logic

- dependabot_file.py
- evergreen.py
- test_dependabot_file.py
Currently we pass in the env variable directly when building a dependabot config file. When iterating through multiple repos, there is a possibility that if one of the previous repos has an existing dependabot config, we land up adding those to the exemption list in order to not add that config again to the dependabot.yml file. We land up using the same exempt_ecosystem for all the foll. repos resulting in skipping of creating that dependabot.yml.
This fix always passes in a copy of the original `exempt_ecosystems` environment variable ensuring the original data is not over written.
```
Checking hello-gh-actions for compatible package managers
before adding exempt_ecosystems:  []
existing_config:  <Contents [.github/dependabot.yaml]>
exempt_ecosystems:  ['gomod', 'docker', …
```
> fix: Ensure exemption list of ecosystem is not overwritten

- dependabot_file.py
- test_dependabot_file.py
fixes https://github.com/github/evergreen/issues/231
Ensure existing dependabot configs without end of file newlines get processed properly so we can add new language configs without a formatting error. See #231 for details on formatting error.
This pull request introduces a new test case to the `test_dependabot_file.py` file to ensure the `dependabot.yml` file is built correctly with bundler and specific configurations. It also modifies the existing config builder code to detect existing newlines and handle the case where one doesn't already exist. The goal of all of this is to prevent writing new language configs starting on the same line as the previous config, breaking the yaml format.
> fix: ensure existing dependabot configs without end of file newlines get processed properly

- .github/workflows/python-ci.yml
- .github/workflows/super-linter.yaml
This pull request improves our OSSF Scorecard and includes updates to the `.github/workflows/super-linter.yaml` file to enhance the CI/CD pipeline by setting up Pythonin order to pin the pip version instead of the previous functionality which upgraded to the latest pip.
use setup python to pin the pip version
> chore: use setup python to pin the pip version

- README.md
Adding a badge to help improve our ossf scorecard score
add the badge
> docs: add ossf badge with link to project details

- test_auth.py
improve auth test coverage by adding invalid and failed app install tests
This pull request introduces new test cases in the `test_auth.py` file to enhance the coverage and robustness of the authentication module. The changes include importing the `requests` library and adding tests for handling request failures and invalid credentials.
> chore: improve auth test coverage

- evergreen.py
In #265 a bug was introduced by removing the continue statement which prevents further processing of issue/pr creation for repositories where no update to the dependabot file was found. This PR just adds the continue statement again. Bug was confirmed by @ricardojdsilva87 already in comment of #265 and a fix is also part of #270.
Right now all evergreen runs fail with an error as soon as the first repository without changes is processed.
> fix: continue on no update for repository

- README.md
- evergreen.py
- test_evergreen.py
This pull request introduces functionality to generate and append a job summary to a GitHub step summary file. The changes include updates to the `evergreen.py` script to create and append the summary, as well as modifications to the `README.md` to document the new job step. Additionally, new tests have been added to ensure the correctness of the new functionality.
* Added code to generate a job summary with details such as organization, follow-up type, dry run status, security updates, and project ID. The summary also includes a table of updated repositories. [[1]](diffhunk://#diff-b2e641407994f0e45d80e45129e5d0388cc50cdfe231fe65d25603aa7c742293R82-R103) [[2]](diffhunk://#diff-b2e641407994f0e45d80e45129e5d0388cc50cdfe231fe65d25603aa7c742293R225-R232) …
> feat: enhance github action summary with detailed repository updates
